### PR TITLE
Instagram Log-in page

### PR DESCRIPTION
**Pull request by the-osiris**
Screenshot (513)

Login Page of Instagram. Please check this out

### CODE REVIEW

**Review by omkar787 — APPROVED** [review]
Appreciate your work, it requires a few changes like changing the year( i.e 2019 to 2021).
But I'll merge this now

**Comment by the-osiris** [comment]
> Appreciate your work, it requires a few changes like changing the year( i.e 2019 to 2021). But I'll merge this now

Yeah! Sorry for that. Actually, Instagram was down here yesterday So I wasn't able to take references so I used google images
Should I change it?

**Comment by omkar787** [comment]
Yeah, it was down here too. And, yes you can do it

**Comment by the-osiris** [comment]
Sure, Give me a minute I'll change it!

**Pull request merged**
